### ISSUE TITLE
Issue in Instagram Connector

### ISSUE THREAD

**Issue by ranijarad** [Esri/instagram-for-geoevent#5]
Hi all
I have faced the following issue and looking forward to be solved 
1) Am not able to use more than one tags , adding two or more tags will cause that GEE will not receive any related data.
2) Instagram will repeat adding same insta message. checking the map and found that same message are repeated very more

**Comment by mzesri** [comment]
The Instagram endpoint for searching by tags only supports single tags. (https://instagram.com/developer/endpoints/tags/?hl=en) The Instagram Input connector didn't do anything extra here.  You could extend the existing input connector by searching for multiple tags yourself and combining the results.

The Instagram Input connector is not a streaming connector.  It is built on top of HTTP Polling transport with a few extra properties.  So, each poll will give you whatever matches the criteria.  It will continue to poll the items that was polled before.  So, you will need to filter the old items out by setting up a filter.  To do this, you may need to use a field calculator to create a new field with the value of $RECEIVED_TIME - timestamp.  Then use a filter to make sure the value of this field is less than the polling interval you set in the properties.

Let me know if this answers your questions.

Thanks,

Ming Zhao
